// Generated by gencpp from file hellocm_msgs/CM2Ext_vhcl.msg
// DO NOT EDIT!


#ifndef HELLOCM_MSGS_MESSAGE_CM2EXT_VHCL_H
#define HELLOCM_MSGS_MESSAGE_CM2EXT_VHCL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hellocm_msgs
{
template <class ContainerAllocator>
struct CM2Ext_vhcl_
{
  typedef CM2Ext_vhcl_<ContainerAllocator> Type;

  CM2Ext_vhcl_()
    : header()
    , time()
    , cycleno(0)
    , synthdelay(0.0)
    , velocity(0.0)
    , heading(0.0)
    , pitch(0.0)
    , roll(0.0)  {
    }
  CM2Ext_vhcl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time()
    , cycleno(0)
    , synthdelay(0.0)
    , velocity(0.0)
    , heading(0.0)
    , pitch(0.0)
    , roll(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _time_type;
  _time_type time;

   typedef int64_t _cycleno_type;
  _cycleno_type cycleno;

   typedef double _synthdelay_type;
  _synthdelay_type synthdelay;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;





  typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> const> ConstPtr;

}; // struct CM2Ext_vhcl_

typedef ::hellocm_msgs::CM2Ext_vhcl_<std::allocator<void> > CM2Ext_vhcl;

typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_vhcl > CM2Ext_vhclPtr;
typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_vhcl const> CM2Ext_vhclConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator1> & lhs, const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.cycleno == rhs.cycleno &&
    lhs.synthdelay == rhs.synthdelay &&
    lhs.velocity == rhs.velocity &&
    lhs.heading == rhs.heading &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator1> & lhs, const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hellocm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3290c3ba936ec21da9927a50bff0314a";
  }

  static const char* value(const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3290c3ba936ec21dULL;
  static const uint64_t static_value2 = 0xa9927a50bff0314aULL;
};

template<class ContainerAllocator>
struct DataType< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hellocm_msgs/CM2Ext_vhcl";
  }

  static const char* value(const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Message from CarMaker ROS Node to external ROS Node\n"
"#\n"
"\n"
"# General\n"
"Header  header                                 # General ROS Header (optional)\n"
"time    time                                   # ROS time when message was sent (optional)\n"
"int64   cycleno                                # Cycle number since simulation start (optional)\n"
"float64 synthdelay                             # Synthetic delay to check synchronization \n"
"\n"
"float64 velocity\n"
"float64 heading\n"
"float64 pitch\n"
"float64 roll\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.cycleno);
      stream.next(m.synthdelay);
      stream.next(m.velocity);
      stream.next(m.heading);
      stream.next(m.pitch);
      stream.next(m.roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CM2Ext_vhcl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hellocm_msgs::CM2Ext_vhcl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "cycleno: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cycleno);
    s << indent << "synthdelay: ";
    Printer<double>::stream(s, indent + "  ", v.synthdelay);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLOCM_MSGS_MESSAGE_CM2EXT_VHCL_H
